# Database Connection URL (Notice the added 'jdbc:' at the beginning)
spring.datasource.url=jdbc:postgresql://ep-bold-meadow-a4r9rknb.us-east-1.aws.neon.tech/neondb?sslmode=require

# Database Credentials
spring.datasource.username=neondb_owner
spring.datasource.password=npg_ANJ8e7mpXRdu

# Driver Configuration
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate/JPA Settings (Good to have for Spring Data, it automatically prints SQL queries so you can see what is happening)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update